### ISSUE TITLE
BUGFIXES

### ISSUE THREAD

**Issue by kodokoto** [kodokoto/SC-Website-Project#7]
To Do:

- When shrinking the window, the menu bar goes under the main section, ideally the main section should move right relative to the window horizontal size.
- Link hover goes dark for some reason
- Menu bar size is wonky when max fullscreen

**Comment by ReakyLectum** [comment]
Firefox:
no moving grid,
Main box out of line
menu cut off
Edge:
No moving grid while full screen

**Comment by ReakyLectum** [comment]
![image](https://user-images.githubusercontent.com/1857897/106356284-7affe680-62f6-11eb-8cd9-210caa86c66f.png)
Fire fox

**Comment by kodokoto** [comment]
UPDATE on firefox issue:

Seems like this is a problem directly related to a bug in firefox's devtools, and it is not an issue with the code in itself.

https://stackoverflow.com/questions/58855905/transform-rotate-throws-warnings-in-firefox

**Comment by kodokoto** [comment]
Fixed bug 1 and 2

**Comment by Denimbeard** [comment]
dots on menu, menu header is not lined up correctly

**Comment by kodokoto** [comment]
> dots on menu, menu header is not lined up correctly



> Firefox:
> no moving full screen or hal grid,
> Main box out of line
> menu cut off
> Edge:
> No moving grid while full screen

Fixed all but firefox

**Comment by kodokoto** [comment]
Closing issue and merging mockup to main as firefox issue cannot be fixed from our end.
